# Generated by Django 5.2.17 on 2026-08-05 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["user", "-updated_at"], name="notes_user_updated_idx"),
        ),
    ]
